### ISSUE TITLE
API that return random mnemonic

### ISSUE THREAD

**Issue by iphadey** [iphadey/api-hug#15]
I need an API that returns a random X word mnemonic and also its entropy, The X refers to a parameter that passes by the user and by default is 8 words. You may refer to [furqansiddiqui/bip39-mnemonic-php](https://packagist.org/packages/furqansiddiqui/bip39-mnemonic-php) package

**Comment by metallurgical** [comment]
Create PR https://github.com/iphadey/api-hug/pull/19 . hopefully it helps. Thanks
